In [42]:
file = "BAH2021/bahwo21"

In [43]:
ranks = [
    "MHA",
    "E-0",
    "E-0.1",
    "E-0.2",
    "E-1",
    "E-2",
    "E-3",
    "E-4",
    "E-5",
    "E-6",
    "E-7",
    "E-8",
    "E-9",
    "W-1",
    "W-2",
    "W-3",
    "W-4",
    "W-5",
    "O-1E",
    "O-2E",
    "O-3E",
    "O-1",
    "O-2",
    "O-3",
    "O-4",
    "O-5",
    "O-6",
    "O-7"
]

In [44]:
import pandas as pd
df = pd.read_csv(f"{file}.txt", index_col = 0, header=None, names=ranks)

In [45]:
df = df.drop(columns=ranks[1:4])

In [46]:
df

,E-1,E-2,E-3,E-4,E-5,E-6,E-7,E-8,E-9,W-1,...,O-1E,O-2E,O-3E,O-1,O-2,O-3,O-4,O-5,O-6,O-7
MHA,,,,,,,,,,,,,,,,,,,,,
AK400,1380.0,1662.0,1674.0,1743.0,1908.0,2022.0,1677.0,1905.0,2034.0,2235.0,...,1671.0,1764.0,2070.0,2331.0,2400.0,2514.0,2556.0,2556.0,2556.0,2556.0
AK401,1455.0,1758.0,1767.0,1773.0,2013.0,2133.0,1770.0,2010.0,2148.0,2340.0,...,1764.0,1854.0,2187.0,2361.0,2376.0,2397.0,2439.0,2439.0,2439.0,2439.0
AK402,1401.0,1878.0,1887.0,1941.0,2022.0,2178.0,1890.0,1983.0,2199.0,2514.0,...,1884.0,1944.0,2262.0,2592.0,2652.0,2742.0,2793.0,2793.0,2793.0,2793.0
AK403,1248.0,1536.0,1548.0,1635.0,1752.0,1881.0,1560.0,1731.0,1884.0,2073.0,...,1545.0,1638.0,1899.0,2187.0,2274.0,2409.0,2451.0,2451.0,2451.0,2451.0
AK404,1281.0,1566.0,1575.0,1689.0,1833.0,1956.0,1581.0,1776.0,1959.0,2118.0,...,1572.0,1692.0,1962.0,2262.0,2370.0,2541.0,2586.0,2586.0,2586.0,2586.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZZ850,1257.0,1407.0,1500.0,1602.0,1755.0,1821.0,1572.0,1752.0,1827.0,1950.0,...,1491.0,1671.0,1851.0,1995.0,2028.0,2079.0,2115.0,2115.0,2115.0,2115.0
ZZ860,1305.0,1464.0,1560.0,1665.0,1821.0,1890.0,1632.0,1818.0,1896.0,2022.0,...,1551.0,1737.0,1923.0,2067.0,2100.0,2151.0,2190.0,2190.0,2190.0,2190.0
ZZ870,1374.0,1542.0,1641.0,1755.0,1917.0,1986.0,1719.0,1914.0,1992.0,2121.0,...,1635.0,1827.0,2019.0,2166.0,2202.0,2253.0,2292.0,2292.0,2292.0,2292.0
ZZ880,1455.0,1635.0,1743.0,1860.0,2028.0,2100.0,1821.0,2025.0,2109.0,2238.0,...,1734.0,1935.0,2133.0,2286.0,2322.0,2376.0,2418.0,2418.0,2418.0,2418.0
ZZ890,1668.0,1875.0,2001.0,2133.0,2319.0,2397.0,2088.0,2316.0,2406.0,2547.0,...,1989.0,2217.0,2433.0,2595.0,2634.0,2691.0,2739.0,2739.0,2739.0,2739.0

In [47]:
with open(f"{file}.csv", "w") as f:
    f.write(df.to_csv())